--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dwagn/wallpapers/0070.jpg"

-- Special
background="#061617"
foreground="#caccd0"
cursor="#caccd0"

-- Colors
color0="#061617"
color1="#5C6867"
color2="#7C8470"
color3="#757D83"
color4="#7B8389"
color5="#8B9097"
color6="#9A9FA5"
color7="#caccd0"
color8="#8d8e91"
color9="#5C6867"
color10="#7C8470"
color11="#757D83"
color12="#7B8389"
color13="#8B9097"
color14="#9A9FA5"
color15="#caccd0"
