# Shell variables
# Generated by 'wal'
wallpaper='/home/dwagn/wallpapers/aron-marinelli-J69cxh_84gg-unsplash.jpg'

# Special
background='#121f24'
foreground='#cfdbd9'
cursor='#cfdbd9'

# Colors
color0='#121f24'
color1='#89917A'
color2='#A0997F'
color3='#5C7788'
color4='#6E998B'
color5='#8D9886'
color6='#9CA698'
color7='#cfdbd9'
color8='#909997'
color9='#89917A'
color10='#A0997F'
color11='#5C7788'
color12='#6E998B'
color13='#8D9886'
color14='#9CA698'
color15='#cfdbd9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
