# Shell variables
# Generated by 'wal'
wallpaper='/home/dwagn/wallpapers/0070.jpg'

# Special
background='#061617'
foreground='#caccd0'
cursor='#caccd0'

# Colors
color0='#061617'
color1='#5C6867'
color2='#7C8470'
color3='#757D83'
color4='#7B8389'
color5='#8B9097'
color6='#9A9FA5'
color7='#caccd0'
color8='#8d8e91'
color9='#5C6867'
color10='#7C8470'
color11='#757D83'
color12='#7B8389'
color13='#8B9097'
color14='#9A9FA5'
color15='#caccd0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
