--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dwagn/wallpapers/aron-marinelli-J69cxh_84gg-unsplash.jpg"

-- Special
background="#121f24"
foreground="#cfdbd9"
cursor="#cfdbd9"

-- Colors
color0="#121f24"
color1="#89917A"
color2="#A0997F"
color3="#5C7788"
color4="#6E998B"
color5="#8D9886"
color6="#9CA698"
color7="#cfdbd9"
color8="#909997"
color9="#89917A"
color10="#A0997F"
color11="#5C7788"
color12="#6E998B"
color13="#8D9886"
color14="#9CA698"
color15="#cfdbd9"
