#!/bin/bash 

SESSIONNAME="configs"
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
  then
    tmux new-session -s $SESSIONNAME -n configs -d 
    tmux send-keys -t $SESSIONNAME "~/scripts/all-configs" C-m 
fi

tmux attach -t $SESSIONNAME
